image: Visual Studio 2015

platform:
- x64

environment:
  matrix:
    - BUILD_TYPE: nmake

build_script:
    - cd src
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
    - nmake -f Makefile.x64.msvc.in
